server:
  port: 9210
spring:
  application:
    name: order
  cloud:
    config:
      uri: http://localhost:6661/
      profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sc_sell?characterEncoding=utf-8&useSSL=false
    username: root
    password:
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule