server:
  port: 6661
spring:
  application:
    name: config-center
#  profiles:
#    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/deadliving/config-repo
          # 配置文件本地位置
          basedir: D:/project/owner/java-study/mygithub/springcloud-ex/springcloud-diancan/config-center/src/main/resources/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

