eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9200
spring:
  application:
    name: product
  cloud:
    config:
      uri: http://localhost:6661/
      profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sc_sell?characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    show-sql: true